name: Test

on:
    workflow_dispatch:
        inputs:
            is_minor_branch:
                description: 'Is Minor Branch'
                required: true
                default: 'false'
                type: choice
                options:
                    - 'true'
                    - 'false'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set environment variable using env key in job
        env:
          MY_VAR: "false"
        run: |
          if ('${{ github.event.inputs.is_minor_branch }}' -eq 'true') {
            MY_VAR="true"
          }
          echo "MY_VAR=$MY_VAR"
      
      - name: Set environment variable using env key in step
        run: Write-Host "${{ env.MY_VAR }}"
