name: Test

on:
    workflow_dispatch:
        inputs:
            is_minor_branch:
                description: 'Is Minor Branch'
                required: true
                default: 'false'
                type: choice
                options:
                    - 'true'
                    - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable using env key in job
        env:
          MY_VAR: "some_value"
        run: |
          echo "MY_VAR=$MY_VAR"
      
      - name: Set environment variable using env key in step
        run: |
          MY_VAR="another_value"
          echo "MY_VAR=$MY_VAR"
