name: Test

on:
  workflow_dispatch:
    inputs:
      is_minor_branch:
        description: 'Is Minor Branch'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set environment variable based on input
        run: |
          if ('${{ github.event.inputs.is_minor_branch }}' -eq 'true') {
            echo "MY_VAR=true" >> $GITHUB_ENV
          } else {
            echo "MY_VAR=false" >> $GITHUB_ENV
          }

      - name: Check the environment variable and run if true
        run: |
          if($MY_VAR -eq 'true'){
            Write-Host "Success"
          } else{
            Write-Host "Connectivity KO"
           }
          Write-Host "Failed"