name: Test

on:
  workflow_dispatch:
    inputs:
      is_minor_branch:
        description: 'Is Minor Branch'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: windows-latest
    outputs:
      branch_found: ${{ steps.check_branch.outputs.branch_found }}

    steps:
      - name: Check if the branch exists in the repository
        id: check_branch
        run: |
          $SkipStage = $false
          if('${{ env.IS_MINOR_BRANCH }}' -eq 'true'){
            $SkipStage = $true
          }
          echo "::set-output name=branch_found::$SkipStage"

      - name: Display the result of the branch search
        run: |
          echo "The branch_found value is: ${{ steps.check_branch.outputs.branch_found }}"
