name: Test

on:
    workflow_dispatch:
        inputs:
            is_minor_branch:
                description: 'Is Minor Branch'
                required: true
                default: 'false'
                type: choice
                options:
                    - 'true'
                    - 'false'

jobs:
  Test:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clean workspace
      run: Remove-Item -Recurse -Force *.* -ErrorAction Ignore

    - name: Validate User Input
      run: |
        echo "skipStage=false" >> $GITHUB_ENV
        if ("${{ github.event.inputs.is_minor_branch }}" -eq 'true') {
          echo "skipStage=true" >> $GITHUB_ENV
        }

    - name: Printing Skip stage
      run: |
        Write-Host "${{ env.skipStage }}"
        Write-Host "$env:skipStage"
    
    - name: Skip Stage
      if: ${{ env.skipStage == 'false' }}
      run: Write-Host "SUCCESS"
