jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable using env key in job
        env:
          MY_VAR: "Test"
        run: |
          echo "MY_VAR=$MY_VAR"
      
      - name: Set environment variable using env key in step
        run: |
          MY_VAR="another_value"
          echo "MY_VAR=$MY_VAR"
