name: Test

on:
  workflow_dispatch:
    inputs:
      is_minor_branch:
        description: 'Is Minor Branch'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set environment variable based on input
        run: |
          if ('${{ inputs.is_minor_branch }}' == 'true') {
            echo "MY_VAR=true" >> $GITHUB_ENV
          } else {
            echo "MY_VAR=false" >> $GITHUB_ENV
          }

      - name: Check the environment variable and run if true
        if: ${{ env.MY_VAR == 'true' }}
        run: Write-Host "Success"